### ISSUE TITLE
Change "Limit exceeded, please upgrade your account - 3003" error text

### ISSUE THREAD

**Issue by losnappas** [losnappas/Song-identifier#8]
Users are being tricked into thinking there's a way of buying the addon when this pops up. Don't want that.. Instead, give a hint about making ones own account and checking out the preferences page.

Related: what to do about the limit again, and how much work is it gonna be..?

**Comment by piratesephiroth** [comment]
you should just catch the error code and display the proper message telling the user to create their own account

**Comment by losnappas** [comment]
Got that right. Thanks
